version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    environment:
      - FLASK_APP=app.py
#      - FLASK_ENV=development
    depends_on:
      - redis

  redis:
    image: redis:latest
